### ISSUE TITLE
下载到100%后卡住不动

### ISSUE THREAD

**Issue by FaiChou** [Lakr233/Asspp#1]
![IMG_9154](https://github.com/user-attachments/assets/e6d32be9-2530-4cb2-a35b-3910a6a840e1)

重启后点进去是 Continue Download，点击后还是卡在 100%

**Comment by Lakr233** [comment]
要写一个 Signature 可能存丢了 目前我这边没复现 试试删除重新下载不要关掉 app 呢？

**Comment by FaiChou** [comment]
> 要写一个 Signature 可能存丢了 目前我这边没复现 试试删除重新下载不要关掉 app 呢？

删除重新下载依然卡在100%。我登录的是美区账号。

**Comment by Lakr233** [comment]
![IMG_4188](https://github.com/user-attachments/assets/932011d1-22c5-4005-b89f-fb383edc1b8c)

我这里下载安装都好用。。。
我真的找不到问题在哪 过几天看看有我代码的同学他们怎么说吧

**Comment by missuo** [comment]
一样的问题，到 100% 就卡住了。

![image](https://github.com/user-attachments/assets/8c5264f9-2809-4f4f-ae40-d07eb35d70be)

**Comment by uclort** [comment]
+1 存在相同的问题

**Comment by ikanam** [comment]
相同问题，我的系统是iOS18 Beta，不知道和系统版本有没有关

**Comment by Oranzh** [comment]
那我就不试了，我是18beta3

**Comment by ikanam** [comment]
找到原因了，使用AltStore或者Sideloadly这类工具签名会改变bundleId,使用Wildcard Provisioning Profile重签名就可以用了

**Comment by Lakr233** [comment]
<img width="666" alt="截屏2024-07-12 17 20 16" src="https://github.com/user-attachments/assets/bc8225b2-138e-4406-9348-cc231c06725f">

楼上说的不是完全没可能。。。是不是你们 bundle id 写了什么不能写的

**Comment by akinazuki** [comment]
![telegram-cloud-photo-size-5-6091496200193818768-y](https://github.com/user-attachments/assets/ce26597d-ce3b-4a12-a3b0-cfa0a9469f70)

![telegram-cloud-photo-size-5-6091496200193818769-y](https://github.com/user-attachments/assets/33d8996e-8ef2-45e7-9374-a8665747e697)


在 iOS 17.5.1 上测试通过，没有问题

**Comment by Lakr233** [comment]
确诊是签名工具的问题 不清楚具体原因 尚无法修复 还恳请各位换个签名工具

<img width="285" alt="截屏2024-07-12 17 39 34" src="https://github.com/user-attachments/assets/380461c7-cc0d-4960-9dcb-940ed982654f">

**Comment by Game-2020** [comment]
> 确诊是签名工具的问题 不清楚具体原因 尚无法修复 还恳请各位换个签名工具
> 
> 
> 
> <img width="285" alt="截屏2024-07-12 17 39 34" src="https://github.com/user-attachments/assets/380461c7-cc0d-4960-9dcb-940ed982654f">
> 
> 

请问那个签名工具可以，全能签不行

**Comment by Lakr233** [comment]
签名工具的问题需要自己解决 免费软件不提供技术支持 谢谢理解

**Comment by missuo** [comment]
> 请问那个签名工具可以，全能签不行

在全能签 **证书管理** 查看你的证书是不是 wildcard，如果是的话，例如是 `me.missuo.*`，那你就签名的时候把 Bundle ID 改成 `me.missuo.asspp`，应该就可以了。

**Comment by Lakr233** [comment]
试试 1.2.9 也许修复了

**Comment by gonghao** [comment]
感恩，1.2.9 测试修复了！好奇了解一下原因，跟签名是有什么关系？

**Comment by Lakr233** [comment]
Bundle ID 瞎写了 包含了文件系统不允许的字符 导致下载内容丢失

**Comment by gonghao** [comment]
> Bundle ID 瞎写了 包含了文件系统不允许的字符 导致下载内容丢失

专门解包看了下重新签名后的 IPA 的 Bundle ID 都是正常大小写+. 反复尝试了很多次，真是神奇了 😂
