### ISSUE TITLE
通过airdrop投送的IPA包如何安装？

### ISSUE THREAD

**Issue by Moonbow1999** [Lakr233/Asspp#17]
![image](https://github.com/user-attachments/assets/26168e5c-115f-4294-91ea-395fc1dca514)![image](https://github.com/user-attachments/assets/24830031-df3b-4d16-915e-f051b3948715)
两个前提条件已经满足了 就是不知道如何安装

**Comment by Lakr233** [comment]
可能还需要同一个 iCloud。。。这个我无能为力

**Comment by XueshiQiao** [comment]
> 可能还需要同一个 iCloud。。。这个我无能为力

友好同问，正常情况下是怎么安装投递过来的 ipa 呢？有没有简单的操作指南？
