### ISSUE TITLE
有人能出一个详细的安装教程吗？

### ISSUE THREAD

**Issue by lovejing0306** [Lakr233/Asspp#18]
有人能出一个从 .xcarchive 文件安装到 iOS 手机上的详细教程吗？感激不尽！！！

**Comment by Lakr233** [comment]
https://mp.weixin.qq.com/s/FBkhFSL6_YeTcKEsdpVSpA

**Comment by lovejing0306** [comment]
> https://mp.weixin.qq.com/s/FBkhFSL6_YeTcKEsdpVSpA

但这个教程里面没有给出怎么从 .xcarchive  安装的教程啊？
