### ISSUE TITLE
关于详细安装教程不详细的问题

### ISSUE THREAD

**Issue by lovejing0306** [Lakr233/Asspp#19]
https://github.com/Lakr233/Asspp/issues/18 中给出的安装教程 https://mp.weixin.qq.com/s/FBkhFSL6_YeTcKEsdpVSpA 不详细。教程中只给出了几种安装方式，这些安装方式都需要使用到 ipa 文件。但我们给出的是 Asspp 2024-7-13, 18.32.xcarchive 这个文件，请问这个文件怎么能够得到 ipa 文件？

**Comment by Lakr233** [comment]
你自己想办法 不提供技术支持
