### ISSUE TITLE
如果能iCloud同步账号就更美滋滋了

### ISSUE THREAD

**Issue by birdmichael** [Lakr233/Asspp#2]

**Comment by Lakr233** [comment]
off topic: 你下载是可以用的对吧 为啥 #1 那么多人说不顶用 我有点懵逼

**Comment by birdmichael** [comment]
因为我能想到的最完美的使用场景是跨设备安装.
iPhone给mac tv vr, mac给iPhone...

弥补本地安装的缺点...对另外一台手机安装的衍生...
所以在这个场景下,iCloud能同步账户信息就美滋滋了..

还有一个小优化,如果地区可以添加一个过滤未登陆地区就更美滋滋了
感谢大佬

**Comment by Lakr233** [comment]
> 因为我能想到的最完美的使用场景是跨设备安装. iPhone给mac tv vr, mac给iPhone...
> 
> 弥补本地安装的缺点...对另外一台手机安装的衍生... 所以在这个场景下,iCloud能同步账户信息就美滋滋了..
> 
> 还有一个小优化,如果地区可以添加一个过滤未登陆地区就更美滋滋了 感谢大佬

我拉你进源码仓吧 你帮我实现一下（）😂

**Comment by birdmichael** [comment]
ok~

**Comment by qaz793** [comment]
⼁

**Comment by Lakr233** [comment]
这个版本我打算开源 然后封版

这边的 issue 就先关掉了 后续我们私有仓库跟进吧 不打算面向大众了

**Comment by XueshiQiao** [comment]
> 这个版本我打算开源 然后封版
> 
> 这边的 issue 就先关掉了 后续我们私有仓库跟进吧 不打算面向大众了

求拉私仓

**Comment by hxhlb** [comment]
求拉私仓, 谢谢.

**Comment by Lakr233** [comment]
不认识你们俩 谢谢

**Comment by hxhlb** [comment]
> 不认识你们俩 谢谢

啊, 那就等认识了在找您吧.
感谢回复.

**Comment by XueshiQiao** [comment]
> 不认识你们俩 谢谢

理解，没关系。只是很喜欢这个项目，所以看能否拉私仓。
