### ISSUE TITLE
重复获取许可报错

### ISSUE THREAD

**Issue by lzy0699** [Lakr233/Asspp#3]
感谢大佬开发！！测试了一下，过来反馈。

重复获取许可报错：
未完成操作。(ApplePackage.StoreClient.Error错误2。)

其实返回500状态码是说明已经购买过了。

另外：1.搜索结果不太准确：如这个app：https://apps.apple.com/us/app/sketch-c-offline-compiler-debug/id978527183
用sketch c进行搜索，结果里面没这个app，用这个下面的api搜索结果会好些：
'http://itunes.apple.com/search?term=' + $text.URLEncode(keyword) + '&country=' + country + '&entity=software' + '&limit=' + limit
2.建议增加多种搜索方式，如Bundle ID和trackId。
3.也是遇到下载卡100%：系统是ios15.0.2，用的巨魔2安装的，Bundle ID是wiki.qaq.Asspp。感觉是下载的ipa保存路径不对，用filza在docs路径下也找不到下载的临时文件，全屏搜索.ipa文件也找不到。
4.建议增加通过Bundle ID和trackId直接下载的功能，这样可以下载一些已购的下架app。
5.建议增加下载旧版app的功能。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Lakr233** [comment]
1 搜索问题应该不会开刀优化 投入产出很低 我这边在 CN 区域搜索 sketch c 能找到这个软件
2 已经加上 Bundle ID 暂不考虑 Track ID
3 参考 #1 不打算修复 因为要动刀底下一个万年没更新的断点续传的下载框架
4 加上了
5 收费之前不考虑 要接的接口一大坨 不高兴做 我自己没需求
