### ISSUE TITLE
无法添加账号

### ISSUE THREAD

**Issue by happy0853077** [Lakr233/Asspp#4]
换了多个账号都是这个报错
ios16.1.2，se3已越狱，使用巨魔安装
![image](https://github.com/user-attachments/assets/68b289f5-cd33-43bf-9a3c-fa2342133da8)

**Comment by a1286871907** [comment]
同样的问题

**Comment by lzy0699** [comment]
这是没填二次验证码吧。

**Comment by happy0853077** [comment]
他都没发验证码> 这是没填二次验证码吧。

**Comment by happy0853077** [comment]
他都没发验证码> 这是没填二次验证码吧。

**Comment by a1286871907** [comment]
> 他都没发验证码> 这是没填二次验证码吧。
> 我是把圈X关了之后可以收到验证码 把验证码填上还是一样的问题 很奇怪
>

**Comment by Virgo-0910** [comment]
我这里给Apple的分流规则改走直连就没啥问题，走代理就延迟很高或者不弹窗二次验证码

**Comment by Lakr233** [comment]
苹果的服务器不太好用 多点几下 一直没收到的话自己去系统设置拿一个来
