### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by ihaoljy** [Lakr233/Asspp#9]
最新版1.2.9
看下图![image](https://github.com/user-attachments/assets/43890d32-963d-44ea-bb14-394636f86ca3)

**Comment by ihaoljy** [comment]
一直就这样！

**Comment by Lakr233** [comment]
看下设置页面有没有开权限 没有的话点一下看看 如果什么都没有那是设备拒绝了请求

**Comment by ihaoljy** [comment]
> 看下设置页面有没有开权限 没有的话点一下看看 如果什么都没有那是设备拒绝了请求

https://github.com/user-attachments/assets/f543f716-812e-4b46-909d-c9b8eb8f3d97

**Comment by Lakr233** [comment]
啥系统版本？这边没遇到。。。你的软件我可以安装

**Comment by ihaoljy** [comment]
> 啥系统版本？这边没遇到。。。你的软件我可以安装

12pm  17.0

**Comment by Ssttar** [comment]
12 18.0 beta3 一样问题

**Comment by gujiaming2022** [comment]
1.2.10也一样，设置也开了本地网络，巨魔安装17.0

**Comment by Lakr233** [comment]
隔壁有人找到问题了 这个软件最低限制可能高于你当前的系统版本

Asspp 不会支持这类安装 也不会修复系统 itms service 的错误 如果无法发起安装 大概率不是 Asspp 的问题 自己研究吧

**Comment by gujiaming2022** [comment]
> 隔壁有人找到问题了 这个软件最低限制可能高于你当前的系统版本
> 
> Asspp 不会支持这类安装 也不会修复系统 itms service 的错误 如果无法发起安装 大概率不是 Asspp 的问题 自己研究吧

不会啊，我导入轻松签能正常安装😂

**Comment by Ssttar** [comment]
实测是开VPN问题，关掉就可以了，打开就不行

**Comment by gujiaming2022** [comment]
> 1.2.10实测是开VPN问题，关掉就可以了，打开就不行

还真是！解决了

**Comment by Lakr233** [comment]
Futher investigation indicate that proxy software may not correctly resolve the DNS or proxied itms service data stream. 

Make sure following:

- `app.localhost.direct` is resolved to 127.0.0.1
- do not use proxy on this domain
- allow LAN access permission for Asspp in iOS Setting
